steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudeval-255302/eval-multi', '-f', 'eval-docker/multi/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudeval-255302/eval-multi']
